### ISSUE TITLE
Unable to install Qt 6.7 with deps script on Windows

### ISSUE THREAD

**Issue by dk-mushiyoke** [deskflow/deskflow#7513]
### What type of Synergy user are you?

Community user

### Discussion

- [ ] I want to report a bug (I don't want to start a discussion)

### Product name

Synergy 1

### Synergy version number

1.16.0-beta

### Operating systems (OS)

- [X] Windows
- [ ] macOS
- [ ] Linux or Unix
- [ ] Other

### OS versions or Linux distros

Windows 10

### Synergy configuration

host: opensuse slowroll (have to duplicate config.yaml section for tumbleweed but works just fine otherwise)
client: windows 10

### What steps will reproduce the problem?

1. Run `python scripts/install_deps.py` from the Build Quick Start section for windows in readme file

### Log output

```shell
C:\Users\dkong\Tools\synergy>python scripts/install_deps.py
Using virtual environment for: C:\Users\dkong\Tools\synergy\scripts\install_deps.py
Updating pip...
Running: C:\Users\dkong\Tools\synergy\.venv\Scripts\python.exe -m pip install --upgrade pip
Requirement already satisfied: pip in c:\users\dkong\tools\synergy\.venv\lib\site-packages (24.2)
Installing required modules...
Running: C:\Users\dkong\Tools\synergy\.venv\Scripts\python.exe -m pip install -e scripts
Obtaining file:///C:/Users/dkong/Tools/synergy/scripts
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: cmake-format in c:\users\dkong\tools\synergy\.venv\lib\site-packages (from scripts==0.0.1) (0.6.13)
Requirement already satisfied: clang-format in c:\users\dkong\tools\synergy\.venv\lib\site-packages (from scripts==0.0.1) (18.1.8)
Requirement already satisfied: python-dotenv in c:\users\dkong\tools\synergy\.venv\lib\site-packages (from scripts==0.0.1) (1.0.1)
Requirement already satisfied: pyyaml in c:\users\dkong\tools\synergy\.venv\lib\site-packages (from scripts==0.0.1) (6.0.2)
Requirement already satisfied: colorama in c:\users\dkong\tools\synergy\.venv\lib\site-packages (from scripts==0.0.1) (0.4.6)
Requirement already satisfied: meson in c:\users\dkong\tools\synergy\.venv\lib\site-packages (from scripts==0.0.1) (1.5.1)
Requirement already satisfied: gitpython in c:\users\dkong\tools\synergy\.venv\lib\site-packages (from scripts==0.0.1) (3.1.43)
Requirement already satisfied: aqtinstall in c:\users\dkong\tools\synergy\.venv\lib\site-packages (from scripts==0.0.1) (3.1.18)
Requirement already satisfied: bs4 in c:\users\dkong\tools\synergy\.venv\lib\site-packages (from aqtinstall->scripts==0.0.1) (0.0.2)
Requirement already satisfied: defusedxml in c:\users\dkong\tools\synergy\.venv\lib\site-packages (from aqtinstall->scripts==0.0.1) (0.7.1)
Requirement already satisfied: humanize in c:\users\dkong\tools\synergy\.venv\lib\site-packages (from aqtinstall->scripts==0.0.1) (4.10.0)
Requirement already satisfied: patch>=1.16 in c:\users\dkong\tools\synergy\.venv\lib\site-packages (from aqtinstall->scripts==0.0.1) (1.16)
Requirement already satisfied: py7zr>=0.20.6 in c:\users\dkong\tools\synergy\.venv\lib\site-packages (from aqtinstall->scripts==0.0.1) (0.22.0)
Requirement already satisfied: requests>=2.31.0 in c:\users\dkong\tools\synergy\.venv\lib\site-packages (from aqtinstall->scripts==0.0.1) (2.32.3)
Requirement already satisfied: semantic-version in c:\users\dkong\tools\synergy\.venv\lib\site-packages (from aqtinstall->scripts==0.0.1) (2.10.0)
Requirement already satisfied: texttable in c:\users\dkong\tools\synergy\.venv\lib\site-packages (from aqtinstall->scripts==0.0.1) (1.7.0)
Requirement already satisfied: cmakelang>=0.6.13 in c:\users\dkong\tools\synergy\.venv\lib\site-packages (from cmake-format->scripts==0.0.1) (0.6.13)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\dkong\tools\synergy\.venv\lib\site-packages (from gitpython->scripts==0.0.1) (4.0.11)
Requirement already satisfied: six>=1.13.0 in c:\users\dkong\tools\synergy\.venv\lib\site-packages (from cmakelang>=0.6.13->cmake-format->scripts==0.0.1) (1.16.0)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\dkong\tools\synergy\.venv\lib\site-packages (from gitdb<5,>=4.0.1->gitpython->scripts==0.0.1) (5.0.1)
Requirement already satisfied: pycryptodomex>=3.16.0 in c:\users\dkong\tools\synergy\.venv\lib\site-packages (from py7zr>=0.20.6->aqtinstall->scripts==0.0.1) (3.20.0)
Requirement already satisfied: pyzstd>=0.15.9 in c:\users\dkong\tools\synergy\.venv\lib\site-packages (from py7zr>=0.20.6->aqtinstall->scripts==0.0.1) (0.16.1)
Requirement already satisfied: pyppmd<1.2.0,>=1.1.0 in c:\users\dkong\tools\synergy\.venv\lib\site-packages (from py7zr>=0.20.6->aqtinstall->scripts==0.0.1) (1.1.0)
Requirement already satisfied: pybcj<1.1.0,>=1.0.0 in c:\users\dkong\tools\synergy\.venv\lib\site-packages (from py7zr>=0.20.6->aqtinstall->scripts==0.0.1) (1.0.2)
Requirement already satisfied: multivolumefile>=0.2.3 in c:\users\dkong\tools\synergy\.venv\lib\site-packages (from py7zr>=0.20.6->aqtinstall->scripts==0.0.1) (0.2.3)
Requirement already satisfied: inflate64<1.1.0,>=1.0.0 in c:\users\dkong\tools\synergy\.venv\lib\site-packages (from py7zr>=0.20.6->aqtinstall->scripts==0.0.1) (1.0.0)
Requirement already satisfied: brotli>=1.1.0 in c:\users\dkong\tools\synergy\.venv\lib\site-packages (from py7zr>=0.20.6->aqtinstall->scripts==0.0.1) (1.1.0)
Requirement already satisfied: psutil in c:\users\dkong\tools\synergy\.venv\lib\site-packages (from py7zr>=0.20.6->aqtinstall->scripts==0.0.1) (6.0.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\dkong\tools\synergy\.venv\lib\site-packages (from requests>=2.31.0->aqtinstall->scripts==0.0.1) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\dkong\tools\synergy\.venv\lib\site-packages (from requests>=2.31.0->aqtinstall->scripts==0.0.1) (3.8)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\dkong\tools\synergy\.venv\lib\site-packages (from requests>=2.31.0->aqtinstall->scripts==0.0.1) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\dkong\tools\synergy\.venv\lib\site-packages (from requests>=2.31.0->aqtinstall->scripts==0.0.1) (2024.8.30)
Requirement already satisfied: beautifulsoup4 in c:\users\dkong\tools\synergy\.venv\lib\site-packages (from bs4->aqtinstall->scripts==0.0.1) (4.12.3)
Requirement already satisfied: soupsieve>1.2 in c:\users\dkong\tools\synergy\.venv\lib\site-packages (from beautifulsoup4->bs4->aqtinstall->scripts==0.0.1) (2.6)
Building wheels for collected packages: scripts
  Building editable for scripts (pyproject.toml) ... done
  Created wheel for scripts: filename=scripts-0.0.1-0.editable-py3-none-any.whl size=2783 sha256=cccaffa1ef1d8a6eea789a6c86b11f1de4bc89ef7a4cffc1a0ca0fdb9193e391
  Stored in directory: C:\Users\dkong\AppData\Local\Temp\pip-ephem-wheel-cache-9flkz0d9\wheels\db\ab\37\3043c30558bc94ccf4a53047dcfca98d1f1313b863a817a2cd
Successfully built scripts
Installing collected packages: scripts
  Attempting uninstall: scripts
    Found existing installation: scripts 0.0.1
    Uninstalling scripts-0.0.1:
      Successfully uninstalled scripts-0.0.1
Successfully installed scripts-0.0.1
Config for OS: windows
Running script with elevated privileges: C:\Users\dkong\Tools\synergy\scripts\install_deps.py --only-elevated --skip-python --lock-file tmp/elevated.lock --pause-on-exit
Script is running with elevated privileges
Waiting for elevated process to exit: 29052
['.venv\\Scripts\\python', '-m', 'aqt', 'install-qt', '--outputdir', './deps/qt', '--base', 'https://qt.mirror.constant.com/', 'windows', 'desktop', '6.7', 'win64_msvc2019_64']
Running: .venv\Scripts\python -m aqt install-qt --outputdir ./deps/qt --base https://qt.mirror.constant.com/ windows desktop 6.7 win64_msvc2019_64
INFO    : aqtinstall(aqt) v3.1.18 on Python 3.12.6 [CPython MSC v.1940 64 bit (AMD64)]
ERROR   : No versions of Qt exist for spec=6.7 with host=windows, target=desktop, arch=win64_msvc2019_64
Traceback (most recent call last):
  File "C:\Users\dkong\Tools\synergy\scripts\install_deps.py", line 147, in run
    install(args)
  File "C:\Users\dkong\Tools\synergy\scripts\install_deps.py", line 170, in install
    deps.install()
  File "C:\Users\dkong\Tools\synergy\scripts\install_deps.py", line 218, in install
    self.windows()
  File "C:\Users\dkong\Tools\synergy\scripts\install_deps.py", line 247, in windows
    qt.install()
  File "C:\Users\dkong\Tools\synergy\scripts\lib\qt_utils.py", line 55, in install
    cmd_utils.run(
  File "C:\Users\dkong\Tools\synergy\scripts\lib\cmd_utils.py", line 141, in run
    raise RuntimeError(
RuntimeError: Command exited with code 1: .venv\Scripts\python -m aqt install-qt --outputdir ./deps/qt --base https://qt.mirror.constant.com/ windows desktop 6.7 win64_msvc2019_64


Error: Failed to install dependencies
```

### Additional information

python 3.12.6 is installed through choco
the elevated command line with choco installations were all successful
i tried manually install qt 6.7.2 community edition with desktop development and still running into this error
the windows machine does have firewall that is not controlled by me, but i could hit the mirror url just fine (https://qt.mirror.constant.com/)
any help is much appreciated!

**Comment by nbolton** [comment]
Thanks for reporting this bug about the Qt dependency. This appears to be the most significant line:
```
ERROR   : No versions of Qt exist for spec=6.7 with host=windows, target=desktop, arch=win64_msvc2019_64
```

@sithlord48 Did you mention something about vcpkg being better at satisfying Qt dep on Windows? We're using `aqtinstall` right now which has worked pretty well for me, but I'm not sure how others are finding it.

**Comment by danielwoww** [comment]
I'm having a similar problem: 


**Log output**

```
Use --force to reinstall, specify a version to install, or try upgrade.
['.venv\\Scripts\\python', '-m', 'aqt', 'install-qt', '--outputdir', './deps/qt', '--base', 'https://qt.mirror.constant.com/', 'windows', 'desktop', '6.7', 'win64_msvc2019_64']
Running: .venv\Scripts\python -m aqt install-qt --outputdir ./deps/qt --base https://qt.mirror.constant.com/ windows desktop 6.7 win64_msvc2019_64
INFO    : aqtinstall(aqt) v3.1.18 on Python 3.10.6 [CPython MSC v.1932 64 bit (AMD64)]
INFO    : Resolved spec '6.7' to 6.7.3
WARNING : Specified Qt version "6.7.3" did not exist when this version of aqtinstall was released. This may not install properly, but we will try our best.
WARNING : Failed to download checksum for the file 'Updates.xml'. This may happen on unofficial mirrors.
WARNING : Caught ChecksumDownloadFailure, terminating installer workers
ERROR   : Failed to download checksum for the file '6.7.3-0-202409200836qtdeclarative-Windows-Windows_10_22H2-MSVC2019-Windows-Windows_10_22H2-X86_64.7z' from mirrors '['https://download.qt.io']
==============================Suggested follow-up:==============================
* Check your internet connection
* Consider modifying `requests.max_retries_to_retrieve_hash` in settings.ini
* Consider modifying `mirrors.trusted_mirrors` in settings.ini (see https://aqtinstall.readthedocs.io/en/stable/configuration.html#configuration)
usage: aqt [-h] [-c CONFIG]
           {install-qt,install-tool,install-doc,install-example,install-src,list-qt,list-tool,list-doc,list-example,list-src,install,tool,doc,examples,src,help,version}
           ...

Another unofficial Qt Installer.
aqt helps you install Qt SDK, tools, examples and others

options:
  -h, --help            show this help message and exit
  -c CONFIG, --config CONFIG
                        Configuration ini file.

subcommands:
  aqt accepts several subcommands:
  install-* subcommands are commands that install components
  list-* subcommands are commands that show available components

  commands {install|tool|src|examples|doc} are deprecated and marked for removal

  {install-qt,install-tool,install-doc,install-example,install-src,list-qt,list-tool,list-doc,list-example,list-src,install,tool,doc,examples,src,help,version}
                        Please refer to each help message by using '--help' with each subcommand
Traceback (most recent call last):
  File "C:\python\deskflow\deskflow\scripts\install_deps.py", line 147, in run
    install(args)
  File "C:\python\deskflow\deskflow\scripts\install_deps.py", line 170, in install
    deps.install()
  File "C:\python\deskflow\deskflow\scripts\install_deps.py", line 218, in install
    self.windows()
  File "C:\python\deskflow\deskflow\scripts\install_deps.py", line 247, in windows
    qt.install()
  File "C:\python\deskflow\deskflow\scripts\lib\qt_utils.py", line 55, in install
    cmd_utils.run(
  File `"C:\python\deskflow\deskflow\scripts\lib\cmd_utils.py",` line 141, in run
    raise RuntimeError(
RuntimeError: Command exited with code 1: .venv\Scripts\python -m aqt install-qt --outputdir ./deps/qt --base https://qt.mirror.constant.com/ windows desktop 6.7 win64_msvc2019_64

```

Error: Failed to install dependencies`

It seems to detect 6.7.3 as latest version but this does not exist for download

**Comment by nbolton** [comment]
> It seems to detect 6.7.3 as latest version but this does not exist for download

I think maybe this is either an `aqt install-qt` bug or perhaps we're using it wrong. 

Would you mind changing the Qt version number in `config.yaml`?

**Comment by nbolton** [comment]
> Setting it to 6.7.0 solves my issue

Thanks for trying that and confirming.

@dk-mushiyoke @danielwoww Please try PR #7585 (branch `lock-qt-ver`) to see if this solves the issue. I locked the version to 6.7.2 rather than 6.7.0 as this is the latest available.

**Comment by danielwoww** [comment]
@nbolton This works however when running **cmake -B build --preset=windows-release** , I get the following error:

```
-- OpenSSL exe dir: C:/user/deskflow/deskflow/vcpkg_installed/x64-windows/tools/openssl
-- OpenSSL root dir: C:/user/deskflow/deskflow/vcpkg_installed/x64-windows
CMake Error at cmake/Libraries.cmake:496 (find_package):
  Could not find a configuration file for package "Qt6" that is compatible
  with requested version "".

  The following configuration files were considered but not accepted:

    C:/user/deskflow/deskflow/deps/qt/6.7.2/msvc2019_64/lib/cmake/Qt6/Qt6Config.cmake, version: 6.7.2 (64bit)

Call Stack (most recent call first):
  cmake/Libraries.cmake:13 (configure_qt)
  CMakeLists.txt:35 (configure_libs)


-- Configuring incomplete, errors occurred!
```

**Comment by sithlord48** [comment]
> Thanks for reporting this bug about the Qt dependency. This appears to be the most significant line:
> 
> ```
> ERROR   : No versions of Qt exist for spec=6.7 with host=windows, target=desktop, arch=win64_msvc2019_64
> ```
> 
> @sithlord48 Did you mention something about vcpkg being better at satisfying Qt dep on Windows? We're using `aqtinstall` right now which has worked pretty well for me, but I'm not sure how others are finding it.

Yes this can be done.
The main downside to vcpkg is that it has to build all the unfound dependencies on the projects "configuration" step. This can make the first configuration take literal hours (if you need to build something big like Qt on a slower machine). You also really want to have the place vcpkg builds items in  C:\vcpkg (or similar) as long paths become a problem and this way when you build a dependency you don't delete it if you remove a build folder for your project.

**Comment by dk-mushiyoke** [comment]
@nbolton thanks for looking into this, i just tried your branch `lock-qt-ver` and still could not proceed - i can hit all the mirrors and download files just fine in a browser (albeit very slow), but this machine does has a firewall that i dont have control over. would be nice if someone else could give it a try. please see output below

```
['.venv\\Scripts\\python', '-m', 'aqt', 'install-qt', '--outputdir', './deps/qt', '--base', 'https://qt.mirror.constant.com/', 'windows', 'desktop', '6.7.2', 'win64_msvc2019_64']
Running: .venv\Scripts\python -m aqt install-qt --outputdir ./deps/qt --base https://qt.mirror.constant.com/ windows desktop 6.7.2 win64_msvc2019_64
INFO    : aqtinstall(aqt) v3.1.18 on Python 3.12.6 [CPython MSC v.1940 64 bit (AMD64)]
WARNING : Specified Qt version "6.7.2" did not exist when this version of aqtinstall was released. This may not install properly, but we will try our best.
WARNING : Failed to download checksum for the file 'Updates.xml'. This may happen on unofficial mirrors.
WARNING : Connection to 'https://qt.mirror.constant.com/' failed. Retrying with fallback 'https://qt-mirror.dannhauer.de/'.
WARNING : Failed to download checksum for the file 'Updates.xml'. This may happen on unofficial mirrors.
ERROR   : Failure to connect to https://qt-mirror.dannhauer.de/online/qtsdkrepository/windows_x86/desktop/qt6_672/Updates.xml: SSLError
Traceback (most recent call last):
  File "C:\Users\dkong\Tools\deskflow\scripts\install_deps.py", line 147, in run
    install(args)
  File "C:\Users\dkong\Tools\deskflow\scripts\install_deps.py", line 170, in install
    deps.install()
  File "C:\Users\dkong\Tools\deskflow\scripts\install_deps.py", line 218, in install
    self.windows()
  File "C:\Users\dkong\Tools\deskflow\scripts\install_deps.py", line 247, in windows
    qt.install()
  File "C:\Users\dkong\Tools\deskflow\scripts\lib\qt_utils.py", line 55, in install
    cmd_utils.run(
  File "C:\Users\dkong\Tools\deskflow\scripts\lib\cmd_utils.py", line 141, in run
    raise RuntimeError(
RuntimeError: Command exited with code 1: .venv\Scripts\python -m aqt install-qt --outputdir ./deps/qt --base https://qt.mirror.constant.com/ windows desktop 6.7.2 win64_msvc2019_64


Error: Failed to install dependencies
```

**Comment by nbolton** [comment]
> still could not proceed

Oh dear! Ok, let's try to recap what's happening.

Previous error:
```
Running: .venv\Scripts\python -m aqt install-qt --outputdir ./deps/qt --base https://qt.mirror.constant.com/ windows desktop 6.7 win64_msvc2019_64
...
ERROR   : No versions of Qt exist for spec=6.7 with host=windows, target=desktop, arch=win64_msvc2019_64
```

New error:
```
Running: .venv\Scripts\python -m aqt install-qt --outputdir ./deps/qt --base https://qt.mirror.constant.com/ windows desktop 6.7.2 win64_msvc2019_64
...
ERROR   : Failure to connect to https://qt-mirror.dannhauer.de/online/qtsdkrepository/windows_x86/desktop/qt6_672/Updates.xml: SSLError
```

So, it appears that it is finding it, but is getting `SSLError` when trying to connect. Do you get the same error if you run `aqt` manually?
`.venv\Scripts\python -m aqt install-qt --outputdir ./deps/qt --base https://qt.mirror.constant.com/ windows desktop 6.7 win64_msvc2019_64`

**Comment by dk-mushiyoke** [comment]
@nbolton 

> Do you get the same error if you run aqt manually?
yes, i get the same error from running the same aqt command.

>This command seems to work fine for me, but I suspect it uses a different mirror
as previously mentioned my machine comes with a global self signed cert that routes all traffic to a proxy, i suspect it has something to do with the SSL error since aqt works just fine for you. all the mirrors work ok in a browser for me, but none would work with aqt. at this point i think its fine to close this issue as the SSL issue seems to be on my end, unless there is a way to have python bypass cert checks globally i dont think there is anything you guys need to fix. thank you!

**Comment by nbolton** [comment]
> as previously mentioned my machine comes with a global self signed cert that routes all traffic to a proxy, i suspect it has something to do with the SSL error since aqt works just fine for you

Sorry, yes I did see that and meant to reply but got sidetracked. I'm not aware of any way to bypass cert checks in `aqt` but I wonder if perhaps at this point you're best using some other way than `aqt`, like the [Qt Online Installer](https://www.qt.io/download-open-source). As long as you set `CMAKE_PREFIX_PATH` then our CMake config will find it just fine.

**Comment by dk-mushiyoke** [comment]
for future reference I was able to follow [this section](https://requests.readthedocs.io/en/latest/user/advanced/#ssl-cert-verification) of Requests documentation (which aqt internally uses for http calls) and `set REQUESTS_CA_BUNDLE=path/to/pem` environment variable on my windows box, aqt then was able to download and install normally.

**Comment by nbolton** [comment]
> `set REQUESTS_CA_BUNDLE=path/to/pem` environment variable on my windows box

Very nice! I've added it to the [Build Guide](https://github.com/deskflow/deskflow/wiki/Build-Guide#dependencies).
