### ISSUE TITLE
Crash when turning on external monitor

### ISSUE THREAD

**Issue by nicolasfella** [deskflow/deskflow#7681]
### Project

Deskflow

### Deskflow version number

master (181c34e662426f65334a5772c38f0284568b8f86)

### Build type

Local developer build (built it yourself)

### Operating systems (OS)

- [ ] Windows
- [ ] macOS
- [ ] Linux (X11)
- [X] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other

### Wayland on Linux

- [X] I have reviewed the Wayland known issues and my issue is new
- [ ] I am not using Wayland on Linux

### Signing on mac os

- [ ] I have authorized the application to run on my mac
- [X] I am not using Mac os

### OS versions/distros

OpenSUSE Tumbleweed

### Deskflow configuration

Server: OpenSUSE Tumbleweed Plasma Wayland
Client: Fedora 41 Plasma Wayland

### What steps will reproduce the problem?

1. Start Deskflow session between PCs
2. On the server power on a second monitor
3. Crash

### Log output

```shell
[2024-10-14T13:26:04] DEBUG: server enabled
	/home/nico/workspace/deskflow/src/gui/src/MainWindow.cpp:993
[2024-10-14T13:26:04] DEBUG: client disabled
	/home/nico/workspace/deskflow/src/gui/src/MainWindow.cpp:1016
[2024-10-14T13:26:04] DEBUG: restoring main window size
	/home/nico/workspace/deskflow/src/gui/src/MainWindow.cpp:100
[2024-10-14T13:26:04] DEBUG: restoring main window position
	/home/nico/workspace/deskflow/src/gui/src/MainWindow.cpp:106
[2024-10-14T13:26:04] DEBUG: active settings path: /home/nico/.config/Deskflow/Deskflow.conf
	/home/nico/workspace/deskflow/src/gui/src/MainWindow.cpp:276
[2024-10-14T13:26:04] DEBUG: update check disabled
	/home/nico/workspace/deskflow/src/gui/src/MainWindow.cpp:516
[2024-10-14T13:26:04] INFO: starting core server process (desktop mode)
	/home/nico/workspace/deskflow/src/lib/gui/core/CoreProcess.cpp:359
[2024-10-14T13:26:04] DEBUG: core process state changed: stopped -> starting
	/home/nico/workspace/deskflow/src/lib/gui/core/CoreProcess.cpp:676
[2024-10-14T13:26:04] WARNING: QString::arg: 1 argument(s) missing in <p>Heads up!</p><p>Wayland support is experimental and contains bugs.</p><p>Please <a href="%1" style="color: %2">report bugs</a> to us if you find any.</p><p>Happy testing!</p>
	/home/nico/workspace/qt6/qtbase/src/corelib/text/qstring.cpp:9060
[2024-10-14T13:26:05] DEBUG: saving window size and position
	/home/nico/workspace/deskflow/src/gui/src/MainWindow.cpp:127
[2024-10-14T13:26:05] DEBUG: emitting config saving signal
	/home/nico/workspace/deskflow/src/lib/gui/config/ConfigScopes.cpp:66
[2024-10-14T13:26:05] DEBUG: committing app config
	/home/nico/workspace/deskflow/src/lib/gui/config/AppConfig.cpp:198
[2024-10-14T13:26:05] DEBUG: committing server config
	/home/nico/workspace/deskflow/src/gui/src/ServerConfig.cpp:112
[2024-10-14T13:26:05] DEBUG: writing config to filesystem
	/home/nico/workspace/deskflow/src/lib/gui/config/ConfigScopes.cpp:70
[2024-10-14T13:26:06] DEBUG: emitting config saving signal
	/home/nico/workspace/deskflow/src/lib/gui/config/ConfigScopes.cpp:66
[2024-10-14T13:26:06] DEBUG: committing app config
	/home/nico/workspace/deskflow/src/lib/gui/config/AppConfig.cpp:198
[2024-10-14T13:26:06] DEBUG: committing server config
	/home/nico/workspace/deskflow/src/gui/src/ServerConfig.cpp:112
[2024-10-14T13:26:06] DEBUG: writing config to filesystem
	/home/nico/workspace/deskflow/src/lib/gui/config/ConfigScopes.cpp:70
[2024-10-14T13:26:06] DEBUG: core connection state changed: 1
	/home/nico/workspace/deskflow/src/gui/src/MainWindow.cpp:866
[2024-10-14T13:26:06] INFO: core config file: /home/nico/.config/Deskflow/deskflow-server.conf
	/home/nico/workspace/deskflow/src/lib/gui/core/CoreProcess.cpp:572
[2024-10-14T13:26:06] DEBUG: persisting tls certificate
	/home/nico/workspace/deskflow/src/lib/gui/tls/TlsUtility.cpp:50
[2024-10-14T13:26:06] DEBUG: tls certificate already exists
	/home/nico/workspace/deskflow/src/lib/gui/tls/TlsUtility.cpp:53
[2024-10-14T13:26:06] DEBUG: log level: INFO
	/home/nico/workspace/deskflow/src/lib/gui/core/CoreProcess.cpp:398
[2024-10-14T13:26:06] INFO: running command: /home/nico/kde/usr/bin/deskflow-server -f --no-tray --debug INFO --name dumbledore --enable-crypto --address :24800 -c /home/nico/.config/Deskflow/deskflow-server.conf --tls-cert /home/nico/.deskflow/SSL/Deskflow.pem
	/home/nico/workspace/deskflow/src/lib/gui/core/CoreProcess.cpp:268
[2024-10-14T13:26:06] DEBUG: core process state changed: starting -> started
	/home/nico/workspace/deskflow/src/lib/gui/core/CoreProcess.cpp:676
[2024-10-14T13:26:06] DEBUG: recording that core has started
	/home/nico/workspace/deskflow/src/gui/src/MainWindow.cpp:828
[2024-10-14T13:26:06] DEBUG: emitting config saving signal
	/home/nico/workspace/deskflow/src/lib/gui/config/ConfigScopes.cpp:66
[2024-10-14T13:26:06] DEBUG: committing app config
	/home/nico/workspace/deskflow/src/lib/gui/config/AppConfig.cpp:198
[2024-10-14T13:26:06] DEBUG: committing server config
	/home/nico/workspace/deskflow/src/gui/src/ServerConfig.cpp:112
[2024-10-14T13:26:06] DEBUG: writing config to filesystem
	/home/nico/workspace/deskflow/src/lib/gui/config/ConfigScopes.cpp:70
[2024-10-14T13:26:06] INFO: using ei screen for wayland
	/home/nico/workspace/deskflow/src/lib/deskflow/ServerApp.cpp:566
[2024-10-14T13:26:07] DEBUG: core connection state changed: 3
	/home/nico/workspace/deskflow/src/gui/src/MainWindow.cpp:866
[2024-10-14T13:26:06] NOTE: started server, waiting for clients
	/home/nico/workspace/deskflow/src/lib/deskflow/ServerApp.cpp:521
[2024-10-14T13:26:07] INFO: accepted secure socket
	/home/nico/workspace/deskflow/src/lib/net/SecureSocket.cpp:405
[2024-10-14T13:26:07] INFO: network encryption protocol: TLSv1.3
	/home/nico/workspace/deskflow/src/lib/net/InverseSockets/SslLogger.cpp:114
[2024-10-14T13:26:07] NOTE: accepted client connection
	/home/nico/workspace/deskflow/src/lib/server/ClientListener.cpp:165
[2024-10-14T13:26:07] INFO: local languages: en
	/home/nico/workspace/deskflow/src/lib/deskflow/languages/LanguageManager.cpp:45
[2024-10-14T13:26:07] DEBUG: core connection state changed: 2
	/home/nico/workspace/deskflow/src/gui/src/MainWindow.cpp:866
[2024-10-14T13:26:07] DEBUG: skipping dev thanks message
	/home/nico/workspace/deskflow/src/gui/src/MainWindow.cpp:752
[2024-10-14T13:26:07] NOTE: client "notfedora" has connected
	/home/nico/workspace/deskflow/src/lib/server/Server.cpp:329
[2024-10-14T13:26:08] NOTE: logical output size: 3840x1080@0.0
	/home/nico/workspace/deskflow/src/lib/platform/EiScreen.cpp:414
[2024-10-14T13:26:08] NOTE: logical output size: 3840x1080@0.0
	/home/nico/workspace/deskflow/src/lib/platform/EiScreen.cpp:414
[2024-10-14T13:26:08] NOTE: failed to create xkb context: Resource temporarily unavailable
	/home/nico/workspace/deskflow/src/lib/platform/EiKeyState.cpp:66
[2024-10-14T13:26:08] NOTE: logical output size: 3840x1080@0.0
	/home/nico/workspace/deskflow/src/lib/platform/EiScreen.cpp:414
[2024-10-14T13:26:08] WARNING: failed to apply barrier 2 (1920/0-1920/1079)
	/home/nico/workspace/deskflow/src/lib/platform/PortalInputCapture.cpp:207
[2024-10-14T13:26:08] WARNING: failed to apply barrier 7 (1920/0-1920/1079)
	/home/nico/workspace/deskflow/src/lib/platform/PortalInputCapture.cpp:207
[2024-10-14T13:26:13] INFO: switch from "dumbledore" to "notfedora" at 1876,1364
	/home/nico/workspace/deskflow/src/lib/server/Server.cpp:441
[2024-10-14T13:26:13] INFO: leaving screen
	/home/nico/workspace/deskflow/src/lib/deskflow/Screen.cpp:138
[2024-10-14T13:26:14] INFO: switch from "notfedora" to "dumbledore" at 3,614
	/home/nico/workspace/deskflow/src/lib/server/Server.cpp:441
[2024-10-14T13:26:14] INFO: entering screen
	/home/nico/workspace/deskflow/src/lib/deskflow/Screen.cpp:123
=================================================================
==271972==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x50600005f168 at pc 0x0000004f90bd bp 0x7f53463ff270 sp 0x7f53463ff268
READ of size 1 at 0x50600005f168 thread T6
    #0 0x4f90bc in deskflow::PortalInputCapture::cb_disabled(_XdpInputCaptureSession*) /home/nico/workspace/deskflow/src/lib/platform/PortalInputCapture.cpp:272
    #1 0x4fa7e6 in deskflow::PortalInputCapture::cb_disabled_cb(_XdpInputCaptureSession*, void*) /home/nico/workspace/deskflow/src/./lib/platform/PortalInputCapture.h:66
    #2 0x7f5351db58b7 in g_closure_invoke ../gobject/gclosure.c:833
    #3 0x7f5351dc9572 in signal_emit_unlocked_R ../gobject/gsignal.c:3887
    #4 0x7f5351dcaf88 in signal_emit_valist_unlocked ../gobject/gsignal.c:3519
    #5 0x7f5351dd0a11 in g_signal_emit_valist ../gobject/gsignal.c:3262
    #6 0x7f5351dd0abe in g_signal_emit ../gobject/gsignal.c:3582
    #7 0x7f53538fbf49  (/lib64/libportal.so.1+0x9f49) (BuildId: b73efc8ca59018600f05820ac52dbe0f6fefccc1)
    #8 0x7f535171f28a in emit_signal_instance_in_idle_cb ../gio/gdbusconnection.c:4189
    #9 0x7f535151b70d in g_idle_dispatch ../glib/gmain.c:6243
    #10 0x7f535151deb7 in g_main_dispatch ../glib/gmain.c:3357
    #11 0x7f535151deb7 in g_main_context_dispatch_unlocked ../glib/gmain.c:4208
    #12 0x7f535151fca7 in g_main_context_iterate_unlocked ../glib/gmain.c:4273
    #13 0x7f53515204bb in g_main_context_iteration ../glib/gmain.c:4338
    #14 0x4fa6f3 in deskflow::PortalInputCapture::glib_thread(void*) /home/nico/workspace/deskflow/src/lib/platform/PortalInputCapture.cpp:401
    #15 0x4fe56c in TMethodJob<deskflow::PortalInputCapture>::run() (/home/nico/kde/usr/bin/deskflow-server+0x4fe56c) (BuildId: 7c0051633250e830bdfd9d641287b92be117e7cc)
    #16 0x674224 in Thread::threadFunc(void*) /home/nico/workspace/deskflow/src/lib/mt/Thread.cpp:112
    #17 0x4230be in ArchMultithreadPosix::doThreadFunc(ArchThreadImpl*) /home/nico/workspace/deskflow/src/lib/arch/unix/ArchMultithreadPosix.cpp:648
    #18 0x422eca in ArchMultithreadPosix::threadFunc(void*) /home/nico/workspace/deskflow/src/lib/arch/unix/ArchMultithreadPosix.cpp:631
    #19 0x7f5353262cd5 in asan_thread_start ../../../../libsanitizer/asan/asan_interceptors.cpp:234
    #20 0x7f5350e983b1 in start_thread /usr/src/debug/glibc-2.40/nptl/pthread_create.c:447
    #21 0x7f5350f1d5fb in __clone3 ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
0x50600005f168 is located 8 bytes after 64-byte region [0x50600005f120,0x50600005f160)
allocated by thread T5 here:
    #0 0x7f53532fc777 in malloc ../../../../libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x7f5351526c5d in g_malloc ../glib/gmem.c:100
Thread T6 created by T0 here:
    #0 0x7f53532f4601 in pthread_create ../../../../libsanitizer/asan/asan_interceptors.cpp:245
    #1 0x4209cd in ArchMultithreadPosix::newThread(void* (*)(void*), void*) /home/nico/workspace/deskflow/src/lib/arch/unix/ArchMultithreadPosix.cpp:338
    #2 0x673618 in Thread::Thread(IJob*) /home/nico/workspace/deskflow/src/lib/mt/Thread.cpp:33
    #3 0x4f6570 in deskflow::PortalInputCapture::PortalInputCapture(deskflow::EiScreen*, IEventQueue*) /home/nico/workspace/deskflow/src/lib/platform/PortalInputCapture.cpp:49
    #4 0x4e53e2 in deskflow::EiScreen::EiScreen(bool, IEventQueue*, bool) /home/nico/workspace/deskflow/src/lib/platform/EiScreen.cpp:72
    #5 0x4872e9 in ServerApp::createScreen() /home/nico/workspace/deskflow/src/lib/deskflow/ServerApp.cpp:568
    #6 0x485f0c in ServerApp::openServerScreen() /home/nico/workspace/deskflow/src/lib/deskflow/ServerApp.cpp:479
    #7 0x485468 in ServerApp::initServer() /home/nico/workspace/deskflow/src/lib/deskflow/ServerApp.cpp:437
    #8 0x4866ce in ServerApp::startServer() /home/nico/workspace/deskflow/src/lib/deskflow/ServerApp.cpp:501
    #9 0x48a03e in ServerApp::startNode() /home/nico/workspace/deskflow/src/lib/deskflow/ServerApp.cpp:840
    #10 0x48e615 in AppUtilUnix::startNode() /home/nico/workspace/deskflow/src/lib/deskflow/unix/AppUtilUnix.cpp:51
    #11 0x488b67 in ServerApp::mainLoop() /home/nico/workspace/deskflow/src/lib/deskflow/ServerApp.cpp:702
    #12 0x489f4b in ServerApp::standardStartup(int, char**) /home/nico/workspace/deskflow/src/lib/deskflow/ServerApp.cpp:809
    #13 0x48e48a in standardStartupStatic(int, char**) /home/nico/workspace/deskflow/src/lib/deskflow/unix/AppUtilUnix.cpp:44
    #14 0x489c3a in ServerApp::runInner(int, char**, ILogOutputter*, int (*)(int, char**)) /home/nico/workspace/deskflow/src/lib/deskflow/ServerApp.cpp:787
    #15 0x48e55f in AppUtilUnix::run(int, char**) /home/nico/workspace/deskflow/src/lib/deskflow/unix/AppUtilUnix.cpp:48
    #16 0x47d6bd in App::run(int, char**) /home/nico/workspace/deskflow/src/lib/deskflow/App.cpp:130
    #17 0x41650f in main /home/nico/workspace/deskflow/src/cmd/deskflows/deskflows.cpp:51
    #18 0x7f5350e2a2ad in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
Thread T5 created by T0 here:
    #0 0x7f53532f4601 in pthread_create ../../../../libsanitizer/asan/asan_interceptors.cpp:245
    #1 0x7f535154e223 in g_system_thread_new ../glib/gthread-posix.c:761
SUMMARY: AddressSanitizer: heap-buffer-overflow /home/nico/workspace/deskflow/src/lib/platform/PortalInputCapture.cpp:272 in deskflow::PortalInputCapture::cb_disabled(_XdpInputCaptureSession*)
Shadow bytes around the buggy address:
  0x50600005ee80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x50600005ef00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x50600005ef80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x50600005f000: 00 00 00 00 00 00 00 06 fa fa fa fa 00 00 00 00
  0x50600005f080: 00 00 00 00 fa fa fa fa fd fd fd fd fd fd fd fd
=>0x50600005f100: fa fa fa fa 00 00 00 00 00 00 00 00 fa[fa]fa fa
  0x50600005f180: 00 00 00 00 00 00 00 00 fa fa fa fa 00 00 00 00
  0x50600005f200: 00 00 00 00 fa fa fa fa 00 00 00 00 00 00 00 00
  0x50600005f280: fa fa fa fa 00 00 00 00 00 00 00 fa fa fa fa fa
  0x50600005f300: 00 00 00 00 00 00 00 fa fa fa fa fa 00 00 00 00
  0x50600005f380: 00 00 00 00 fa fa fa fa fd fd fd fd fd fd fd fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==271972==ABORTING
```

**Comment by nbolton** [comment]
Good report, will try to repro. Comes from `deskflow::PortalInputCapture` so it's likely this is not an upstream bug.

**Comment by sithlord48** [comment]
I also suspect this is upstream as i made a report about losing the portal (https://bugs.kde.org/show_bug.cgi?id=494410)

**Comment by nicolasfella** [comment]
https://bugs.kde.org/show_bug.cgi?id=494410 is likely caused by xdg-desktop-portal-kde crashing. I tried to reproduce that and got this crash. I don't see how Deskflow crashing is not a Deskflow bug, even if xdg-desktop-portal-kde is crashing this shouldn't cause Deskflow to crash

**Comment by sithlord48** [comment]
Well Deskflow is using a now invalid object and tries to access it won't it crash ? 
Ill Reopen as we should see if we can at least do something about that case @nbolton
